[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:mariadb]
command=/usr/bin/mysqld_safe --datadir=/var/lib/mysql
autostart=true
autorestart=true
priority=10
stdout_logfile=/var/log/mariadb.log
stderr_logfile=/var/log/mariadb.err

[program:strapi]
command=/bin/bash -c "cd /app/blog-cms && npm run develop"
autostart=true
autorestart=true
priority=20
environment=HOST="0.0.0.0",PORT="1337",DATABASE_CLIENT="mysql",DATABASE_HOST="127.0.0.1",DATABASE_PORT="3306",DATABASE_NAME="blog",DATABASE_USERNAME="root",DATABASE_PASSWORD="@root123",APP_KEYS="lxLQVuOI4c5zA+U76ZTChw==,wzayKU1ID4OPqF87tvR9YQ==,+iq3/kDD1phTgaqCoHSxcA==,hsIt2H6w+kFweiiByuPKtw==",API_TOKEN_SALT="AoQ7/6hERXSLanFWkRWazg==",ADMIN_JWT_SECRET="qMtK16lGuJXSuvtG1Cuu1w==",JWT_SECRET="/yLEiwPHuYLCFGFxN27OAQ==",TRANSFER_TOKEN_SALT="KBgcYG7j1Dc6WUHIEL2+IA==",ENCRYPTION_KEY="V+vIeG92Faa2mOjC7+fxTA=="
stdout_logfile=/var/log/strapi.log
stderr_logfile=/var/log/strapi.err

[program:astro]
command=/bin/bash -c "cd /app/regular-resonance && until nc -z 127.0.0.1 1337; do sleep 2; done; until curl -s http://127.0.0.1:1337/api/articles > /dev/null; do sleep 2; done; npm run build && npx astro preview --host 0.0.0.0 --port 4321"
autostart=true
autorestart=true
priority=30
environment=STRAPI_URL="http://127.0.0.1:1337",PUBLIC_STRAPI_URL="http://localhost:1337",HOST="0.0.0.0",PORT="4321"
stdout_logfile=/var/log/astro.log
stderr_logfile=/var/log/astro.err
